package com.example.meldcxappscheduler.data

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.meldcxappscheduler.data.database.AppDao
import kotlinx.parcelize.Parcelize

// Created by @author Moniruzzaman on 20/9/23. github: filelucker

@Parcelize
@Entity(tableName = "app_schedule_store_table")
data class AppScheduleStore(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val packageId: String,
    val time: String,
    val timeLabel: String
) : Parcelable